[project]
name = "crisp-dm-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "nbformat>=5.10.4",
    "open-interpreter>=0.4.3",
    "pandas>=2.3.3",
    "seaborn>=0.13.2",
]
